### ISSUE TITLE
Router boards

### ISSUE THREAD

**Issue by samuk** [ajokela/tinycomputers.io#1]
Your CM4 comparison was useful. I did a bit of looking around here: https://community.twistedfields.com/t/alternative-cm4-modules/334 

I saw you were planning to do a router, It's also a use case I'm interested in. Did you consider looking at OpenWRT for it? They support the A311D https://github.com/hyphop/khadas-openwrt#readme

Some Wifi cards/ carrier boards I've looked at are here: https://github.com/markqvist/Reticulum/discussions/179

**Comment by ajokela** [comment]
@samuk thanks for checking out my write-up!  I am really unfamilar with OpenWRT.  From the bit of sleuthing I did after I saw your comment, it looks like out-of-box the RPi CM4 should work.  Seeed Studio has a router board that they say is specifically for OpenWRT and the CM4 - https://www.seeedstudio.com/Rapberry-Pi-CM4-Dual-GbE-Carrier-Board-p-4874.html.

If I understand the concept of device overlays (here is an explainer: https://bootlin.com/blog/using-device-tree-overlays-example-on-beaglebone-boards/), there would need to be overlays that OpenWRT would need to include to be able to use the alternatives to the RPi CM4.  I'm really versed on things-overlays, so I could have this wrong.'

My intent for making simple routers using the compute modules is something along the lines of this: https://kifarunix.com/configure-ubuntu-20-04-as-linux-router/

**Comment by samuk** [comment]
>out-of-box the RPi CM4 

Indeed, but where's the fun in that :)

If I can get hold of a BPI board at some point I'll see if that Khadas kernel will boot in it and investigate the overlays further

**Comment by samuk** [comment]
Radxa CM5 looks quite nice too https://wiki.radxa.com/Rock5/CM

**Comment by ajokela** [comment]
CM5 does look cool.  I’ll have to inquire about getting one…
